name: CI with JUnit Report

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies and run tests
      run: |
        set -x
        mkdir -p deps
        git clone ${{ vars.VERSIONERS_URI }} deps/versioners
        cd deps/versioners
        make install
        cd ../../
        git clone ${{ vars.SHUNIT_URI }} deps/shunit
        cd deps/shunit
        make install
        cd ../../
        make test-ci
        cat junit.xml
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: 'junit.xml'
        annotate_only: true
        include_passed: true
